### PR TITLE
classList support, tagName and ancestor finder

### PR DESCRIPTION
**Pull request by K-Adam**

### CODE REVIEW

**Comment by K-Adam** [comment]
This repository looks abandoned, so I published my changes as [K-Adam/elm-dom](https://package.elm-lang.org/packages/K-Adam/elm-dom/latest/)

**Comment by debois** [comment]
Hi @K-Adam., sorry to be slow to respond. I'm not actively working on Elm, but I'd be happy to either (a) add you as a collaborator on this repo, or (b) put a notice in README here that your fork is preferable?

**Comment by K-Adam** [comment]
Hi!

No problem. If you are not actively working on it anymore, then I would suggest you to put a notice in the README with a link to the new fork, and archive this repository.

**Comment by debois** [comment]
Sure. Could you post a PR to that effect?

**Comment by K-Adam** [comment]
I submitted a new pull request with the updated readme: #16 
After accepting that pull request, you can archive the repository by following [this guide](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-repositories)

**Pull request closed without merging**
